# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbf88b659f1610a941a7af1511dbb4a8acb171db5859e2a8b3734ea614330b24a832bbb83d3e9fb1f96963fb7b9ba8d7e9fa19cf7a1e4d5a2ba8de2e5a670b91

test:
  secret_key_base: 4e0e4f2ed98f1df151c170bc436666b5aa9b29fc07934ab60cca756c8330ff71e09428796ca9fa37461113678b8541dc5e48a19ca91196e48ad62d14ebd2e592

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
